# DreamBot 
# Global Conf
log: 
 Console_Enable: true
 Console_Log_Level: debug
 Color: true
 File_Enable: true
 logfile: main.log
 File_Log_Level: debug

http:
  enable: true
  server: 0.0.0.0
  port: 33225

onebot:
  key: 0000000000000000